language: node_js
node_js:
- 6.4
addons:
  sauce_connect: true
  jwt:
    secure: c83aLuh7WI2J0P8LvCHLv8xKcCcx0+prb06JAbejOhpUvGQFkp+6csWtb07RcSbkLXh/61aAfL4PqwLD0KCjxKzoho2wVDaCheRBU8jfZkyQcshbvXQfoEyAIzkIKM/PekDRZBHBB1IcKhlsNXlwBU2rHzZEFEloO6SC4P6ER7J0J/G0I4LzJYZkde3TSc1Ouh0vF2tUlZ243YfWTintEuHuyH/fr3zqBkmj1y7MakQ3T2so0qFNRtm5X9HMwwexc8leXYyToNPUuVAmInkg8CJgBDrfISq0hPLMzRV3Es2AeQv+ZAtAR6HEFXhkU5RsU6Fm6rK/W3eCfoP7Te4CBPm1CaNlJLGHTFJR3qof5Delx+U2nxySLGn1nKihktDS49l+k8icSOYHl/ivRBO7vHaUZnyiKuorgjRkXuAlj5LOrhFWSee0BMCskgSW3fMLmvsrqdODSPhmbnwzKAYfDlIVoftF7ZshFq1VCfW+ol7opJlIoaHNGc1R32CBlicRpfIKx3wwBF6aJJJkiSySteR7XnTaI+8KaG8SW9TvAkJ+u581ULW7pwh24MPyw49aEVHKfaG5vG1kdAeE08zIRXgcqwxE1X+hHjuP0wD/phLgSAZ5WC70JNVsqoGQsH1gePY/Ok/vjhq6j46eiNzjqdR1BpVgipZK4pATMif8trI=
